### ISSUE TITLE
[INFRA] Rename the repository and the npm package to `bpmn-visualization-addons`

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-addons#310]
We propose renaming the repository and the npm package to **bpmn-visualization-addons**.

We aim to remove the term "experimental" for the following reasons:
- We received feedback suggesting that "experimental" might discourage potential users from evaluating the library. It could be perceived as being in an early stage of development or lacking in quality.
- The library is sometimes referred to in discussions as "the experimental lib," but we prefer the term "addons lib" as it better reflects the library's purpose.
- To broaden the library's reach and usage, removing "experimental" should facilitate wider adoption.

The repository and npm package names initially included "experimental" (see #5) because we expected more frequent breaking changes than in `bpmn-visualization`. While this remains possible, the library’s quality is on par with `bpmn-visualization`: the code is thoroughly tested, well-documented, and includes a demo to showcase its functionality. Release notes are consistently provided, documenting significant and breaking changes clearly.

In October 2023, the term "experimental" was removed from documentation, demos, and README files as part of #160. This issue now proposes eliminating "experimental" from the repository and npm package names, adopting the simpler and more descriptive **bpmn-visualization-addons**.

Additionally, this new name aligns with the primary library, `bpmn-visualization`, providing consistency and clarity for users. It helps reinforce the relationship between the main library and its extensions, making it easier for users to recognize that these are complementary tools.

## Name proposals and constraints

**Reminder**: the repository name can be up to 31 characters long (see #5).

name | length
---- | ----
bv-experimental-add-ons (former name) | 23
bpmn-visualization-addons | 25
bv-addons | 9

## Tasks

> [!NOTE]
> To find the reference to the "experimental" repository/package, we can use https://github.com/search?q=org%3Aprocess-analytics+bv-experimental&type=code

```[tasklist]
### Repository tasks
- [x] Rename the repository. GitHub provides automatic redirects https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository
- [x] Update the content of the repository: README, package.json, .... to match the new URL #311
- [x] Rename the SonarCloud project key from `process-analytics_bv-experimental-add-ons` to `process-analytics_bpmn-visualization-addons` if possible (https://docs.sonarsource.com/sonarqube/latest/project-administration/project-settings/#updating-the-project-key) and update references in the README #313
- [x] Update the collector of "GitHub repositories statistics" (restricted access)
- [x] Update references to the URL of the repository in all resources of the _process-analytics_ GitHub organization
```

List of URL updates in process-analytics repositories
* bpmn-visualization: https://github.com/process-analytics/bpmn-visualization-js/pull/3168
* .github: https://github.com/process-analytics/.github/pull/35
* bpmn-visualization-examples also require to update the npm package. All changes will be done in a single PR once the new npm package is available

```[tasklist]
### Package and release tasks
- [x] Rename the npm package: update package.json, code and all documentation related to the npm package #316
- [x] Release a new version and publish the new npm package: as this will breaking changes so this must be a minor version https://www.npmjs.com/package/@process-analytics/bpmn-visualization-addons/v/0.8.0
- [x] Clearly document the package rename in the release notes. Use diff example to illustrate how to change the package usage in package.json and imports in the code. We could ref the PR that update the code of the demo for example. https://github.com/process-analytics/bpmn-visualization-addons/releases/tag/v0.8.0
- [x] In the release notes, document Git repo URL update, see https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository https://github.com/process-analytics/bpmn-visualization-addons/releases/tag/v0.8.0
```

```[tasklist]
### Tasks after package rename
- [x] Deprecate the old “experimental” npm package (in npm.js) and advertise the new package in the deprecation message. See https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions (use the CLI to set the deprecation message)
- [x] Update all repositories of the _process-analytics_ GitHub organization to use the new npm package (examples, demos, ...)
- [x] Except in the documentation of `bpmn-visualization-addons`, there is no reference to `bv-experimental-add-ons`, see https://github.com/search?q=org%3Aprocess-analytics+bv-experimental&type=code
```

processs-analytics repositories updated to use the new npm package:
- https://github.com/process-analytics/bonita-day-demo-2023/pull/148
- https://github.com/process-analytics/bpmn-visualization-examples/pull/608

## Information about the `bv-experimental-add-ons` deprecation

![Image](https://github.com/user-attachments/assets/e6d6b301-8d06-4508-bbad-afbad1db6648)

> [!TIP]
> About the deprecation of the experimental npm package
> If we want to introduce real "experimental" addons package, it will be possible to "undeprecate" the package for reuse. See https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

## Remaining references to "bv-experimental-add-ons"

✔ only in the repository documentation

![Image](https://github.com/user-attachments/assets/24ebb40e-1a68-4a4f-a452-2832facb1dab)

**Comment by tbouffard** [comment]
All tasks have been completed, so closing the issue.
